#!/bin/bash
sort -k2 mid.txt -o mid.txt
declare -i x
x=$(wc -l mid.txt | cut -d " " -f 1)
declare -i stuff
stuff=$x

count=0
while [ $stuff -gt 1 ]
do
	stuff=$(expr $stuff / 2)
	((count++))
done
logCount=2^$count

if ! (($stuff == $logCount)); 
then
$logCount=$logCount*2
$logCount=$logCount-$stuff
while [ $stuff -gt -1 ]
do
	$stuff=$stuff-1
	tail -n 1 mid.txt >> mid.txt
done
fi

s=""
y=
combined=
hash=
while IFS= read -r line
do
	if [[ "$s" ]]; then
		y=$line
		combined="$s+$y"
		hash="$(echo -n $combined | md5sum)"
		echo $hash >> mid.txt
		s=""
		y=
	else
		s=$line
	fi
done < "mid.txt"
echo $hash >> top.txt
echo "The final hash is: "
echo $hash
previousHash=$(tail -n 2 top.txt | head -n 1)
echo "The previous hash was: "
echo $previousHash
